server:
  port: 8140
  #应用名称（nacos会将该名称当作服务名称）
spring:
  application:
    name: order-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public